name: Run Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Generate keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > keystore_base64.jks

      - name: Generate empty secrets.properties
        run: |
          touch secrets.properties
          echo KEY_ALIAS=${{ secrets.KEYSTORE_ALIAS }} >> secrets.properties
          echo KEY_PASSWORD=${{ secrets.DEMO_APP_PASSWORD }} >> secrets.properties
          echo KEY_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} >> secrets.properties
          echo KEY_STORE_FILE=keystore_base64.jks >> secrets.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean testDebug

      - name: Assemble app debug APK
        run: ./gradlew assembleDebug

      - name: Upload app APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble app instrumentation tests
        run: ./gradlew assembleDebugAndroidTest

      - name: Upload app test APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - name: Download app test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest

      - id: Auth
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.DEMO_APP_PROJECT_ID }}
          credentials_json: ${{ secrets.FIREBASE_TEST_LAB_AUTH }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Use gcloud CLI
        run: gcloud info

      - name: Run instrumentation tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=MediumPhone.arm